categories = {'1': 'ferry',
              '10': 'motorway',
              '11': 'motorway_link',
              '15': 'trunk',
              '16': 'trunk_link',
              '20': 'primary',
              '21': 'primary_link',
              '25': 'secondary',
              '26': 'secondary_link',
              '30': 'tertiary',
              '31': 'tertiary_link',
              '35': 'unclassified',
              '40': 'residential',
              '45': 'living_street',
              '50': 'service',
              '55': 'road',
              '60': 'track',
              '65': 'unpaved'}

weekdays = {'0': 'monday',
            '1': 'tuesday',
            '2': 'wednesday',
            '3': 'thursday',
            '4': 'friday',
            '5': 'saturday',
            '6': 'sunday'}

months = {'0': 'january',
          '1': 'february',
          '2': 'march',
          '3': 'april',
          '4': 'may',
          '5': 'june',
          '6': 'july',
          '7': 'august',
          '8': 'september',
          '9': 'october',
          '10': 'november',
          '11': 'december'}